### ISSUE TITLE
Exception on InitializeMudBlazorExtensionsAsync

### ISSUE THREAD

**Issue by antouthaya** [fgilde/MudBlazor.Extensions#16]
blazor.webview.js:1 
        
       Could not find 'BlazorJS.addCss' ('BlazorJS' was undefined).
Error: Could not find 'BlazorJS.addCss' ('BlazorJS' was undefined).
    at https://0.0.0.0/_framework/blazor.webview.js:1:328
    at Array.forEach (<anonymous>)
    at s.findFunction (https://0.0.0.0/_framework/blazor.webview.js:1:296)
    at S (https://0.0.0.0/_framework/blazor.webview.js:1:2437)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3325
    at new Promise (<anonymous>)
    at beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3306)
    at https://0.0.0.0/_framework/blazor.webview.js:1:40711
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:38156)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorJS.BlazorJSExtensions.AddCss(IJSRuntime runtime, String cssContent)
   at MudBlazor.Extensions.Helper.JsImportHelper.InitializeMudBlazorExtensionsAsync(IJSRuntime runtime, Boolean force)
   at AerosealUI.Shared.MainLayout.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by lfhenrl** [comment]
Hi  I have the same problem!!

**Comment by fgilde** [comment]
Could one of you provide more Informations please? With a new blank WebAssembly Blazor project I cant reproduce. Looks that you use a NET MAUI-App. Is that correct?

**Comment by antouthaya** [comment]
Yes , it is Maui blazor app

**Comment by lfhenrl** [comment]
I have made sample https://github.com/lfhenrl/MauiApp1.App
Used the standard template and only added 
 builder.Services.AddMudServicesWithExtensions(); in MauiProgram.cs and
     protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
            await JsRuntime.InitializeMudBlazorExtensionsAsync();
        await base.OnAfterRenderAsync(firstRender);
    }
In MainLauout.razor
and it gives the explained error
