### ISSUE TITLE
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: MudBlazor.Extensions/js/components/MoveContent.min.js

### ISSUE THREAD

**Issue by qjoseph** [fgilde/MudBlazor.Extensions#21]
Hello,

I have this error on my server : 

```
Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: http://my-service/_content/MudBlazor.Extensions/js/components/MoveContent.min.js

 at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BlazorJS.BlazorJSExtensions.ImportModuleAsync(IJSRuntime js, String file)
   at BlazorJS.BlazorJSExtensions.ImportModuleAndCreateJsAsync(IJSRuntime js, String file, String jsCreateMethod, Object[] args)
   at MudBlazor.Extensions.Components.Base.MudExJsRequiredBaseComponent`1.ImportModuleAndCreateJsAsync()
   at MudBlazor.Extensions.Components.MoveContent.ImportModuleAndCreateJsAsync()
   at MudBlazor.Extensions.Components.Base.MudExJsRequiredBaseComponent`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

runtime/sdk : .net 7
build chain: -c Release -r linux-x64 --self-contained false

![image](https://user-images.githubusercontent.com/66062300/235941673-e5a83b31-6187-432b-bb3e-7ef5bfee4363.png)

Any idea? The MudExFileDisplay.min.js file doesn't seem to be a problem.

**Comment by qjoseph** [comment]
Fixed in latest version (after 1.7.35).
