### ISSUE TITLE
Error when initializing the page

### ISSUE THREAD

**Issue by Eternion** [fgilde/MudBlazor.Extensions#6]
Hello,

I find your project awesome, but i am faced to a problem when i have tried the MudExObjectEditForm

here you are the code 

```razor
<MudExObjectEditForm OnValidSubmit="@OnSubmit" Value="@MyModel"></MudExObjectEditForm>
@code{
    private Model MyModel { get; set; } = new Model();

    private void OnSubmit()
    {
        
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
            await JsRuntime.InitializeMudBlazorExtensionsAsync();
        await base.OnAfterRenderAsync(firstRender);
    }

    public class Model
    {
        public int Id{ get; set; }
        public string Name{ get; set; }
        public DateTime CreadtionDate{ get; set; }
        public bool Activate{ get; set; }
    }
}
```

I have followed correctly and i have done it several times but i got this error each time i load the page having the form.
I got this error
```
blazor.webview.js:1 
        
Could not find 'mudElementRef.getBoundingClientRect' ('mudElementRef' was undefined).
Error: Could not find 'mudElementRef.getBoundingClientRect' ('mudElementRef' was undefined).
    at https://0.0.0.0/_framework/blazor.webview.js:1:328
    at Array.forEach (<anonymous>)
    at s.findFunction (https://0.0.0.0/_framework/blazor.webview.js:1:296)
    at S (https://0.0.0.0/_framework/blazor.webview.js:1:2442)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3330
    at new Promise (<anonymous>)
    at beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3311)
    at https://0.0.0.0/_framework/blazor.webview.js:1:42799
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:37578)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at MudBlazor.MudCollapse.UpdateHeight()
   at MudBlazor.MudCollapse.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

How to reproduce:
1. create a maui blazor project
2. add prerequisite like in the readme
3. add the code above in the index.razor

Hope it helps, thanks for your work :)

**Comment by fgilde** [comment]
Looks like your mudblazor.js is not loaded. This then is not a case in my project. Have you tested mudblazor components in your Maui solution? 
In your index you need to add `<script async src="_content/MudBlazor/MudBlazor.min.js"></script>`

**Comment by Eternion** [comment]
Yeah you're right my bad 👍
