### ISSUE TITLE
Issue rendering the Dialog on .Net 8 - ServerRendered

### ISSUE THREAD

**Issue by Gopichandar** [fgilde/MudBlazor.Extensions#68]
### Contact Details

gopichandarbe@gmail.com

### What happened?

I have followed the exact steps as mentioned. https://github.com/fgilde/MudBlazor.Extensions?tab=readme-ov-file#setting-up-mudblazorextensions

In using this on .Net 8 and running this in `InteractiveServer` render mode.  

When I call a dialog,  

 var dialog = await DialogService.ShowEx<ShowDialog>("ShowDialog");

I got the following exception, 

```
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at MudBlazor.Extensions.Helper.JsRuntimeExtensions.IsNamespaceAvailableAsync(IJSRuntime js, String ns)
   at MudBlazor.Extensions.Helper.JsImportHelper.InitializeMudBlazorExtensionsCoreAsync(IJSRuntime runtime, Boolean force)
   at MudBlazor.Extensions.Helper.JsImportHelper.GetInitializedJsRuntime(Object field, IJSRuntime fallback)
   at MudBlazor.Extensions.DialogServiceExt.InjectOptionsAsync(IDialogReference dialogReference, DialogOptionsEx options)
   at MudBlazor.Extensions.DialogServiceExt.InjectOptionsAsync(Task`1 dialogReference, DialogOptionsEx options)
   at MudBlazor.Extensions.DialogServiceExt.ShowAndInject(IDialogService dialogService, Type type, String title, DialogOptionsEx options, DialogParameters parameters)
   at MudBlazor.Extensions.Core.MudExDialogReferenceExtensions.AsMudExDialogReferenceAsync[TComponent](Task`1 dialogReference)
```

Note:  This is working fine in `MudBlazor`

### Expected Behavior

Dialog should be should without app crash, 

### Screenshots

![image](https://github.com/fgilde/MudBlazor.Extensions/assets/13073344/b6375637-29af-4938-a446-e956cb40da15)

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

*

### MudBlazor Version

6.11.1

### What browser are you using?

Chrome

### Sample Solution

[MudBlazorExt_Issue.zip](https://github.com/fgilde/MudBlazor.Extensions/files/13771442/MudBlazorExt_Issue.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Can you create and attach a sample solution containming this problem?

**Comment by Gopichandar** [comment]
Atcched the sample sln for reference @fgilde

**Comment by Gopichandar** [comment]
Also tried disabling the prerendering still issue exists.

**Comment by fgilde** [comment]
Where do you attached a sample? Didn't see it.  one info. Ensure that you inject IDialogService not DialogService.

**Comment by Gopichandar** [comment]
[MudBlazorExt_Issue.zip](https://github.com/fgilde/MudBlazor.Extensions/files/13763637/MudBlazorExt_Issue.zip)

**Comment by Gopichandar** [comment]
Hi @fgilde , can you check if you can see the attached zip?

**Comment by fgilde** [comment]
Yes thank you

**Comment by fgilde** [comment]
Ok I'll work on it. It's strange i I dont know why its working with .net6 or 7 but anyway. You can currently workaround it if you want with manually by passing the IJSRuntime like this 

```c#
   [Inject]
   public IDialogService _dialogService { get; set; }

   [Inject]
   IJSRuntime JS { get; set; }

   private async Task OpenDialog()
   {
       DialogOptionsEx options = new DialogOptionsEx() {JsRuntime = JS};
       var dialog = await _dialogService.ShowEx<MyMudDialog>("Your Dialog Title", options);
   }
```

**Comment by Gopichandar** [comment]
Great. Thanks for the workaround.

**Comment by fgilde** [comment]
Ok bug is fixed in 1.7.80 [MudBlazor.Extensions 1.7.80 Nuget](https://www.nuget.org/packages/MudBlazor.Extensions/1.7.80#readme-body-tab)

**Comment by DragoQCC** [comment]
I just wanted to say this issue was super helpful. I was injecting a DialogServs the IDialogService, and as soon as I put it into the IDialogService, it worked just fine.

**Comment by fgilde** [comment]
I'm very happy to hear that
